### ISSUE TITLE
Problems ith some sites, don't let them load properly or don't load at all

### ISSUE THREAD

**Issue by darkhellsatan666** [Brandon-T/Coin-Blocker#2]
Hello again, i want to report a persistent problem present since 1.0, tought it was fixed on 1.0.1 and 1.0.2 but no, still there:

The extension cause problems with some sites, don't let them load properly or don't load at all, please take a look to this example:

This site, http://www.enter.co , as far as i've observed doesn't have  any miner script, at least never observed high cpu usage related to this site, however your plugin apparently blocks something and the page doesn't load, at least not his content, only the background image; i've tryed adding to exception list but the problem persist, BUT, if i disable the extension the page load properly, not problems at all.

I´ve disabled all 3rd party extensions except this to discard any conflict but the problem persist, page loads properly only when i disable your extension.

**Comment by Brandon-T** [comment]
Fixed in the latest release. It'll be on the Firefox Addons and Chrome Addons shortly after it is approved.

Some URLs were slipping through the white-list and still being blocked. I fixed the issue by getting the request's tab and checking if it or a pattern matching it, is in the white-list. Tested and verified on http://enter.co, gmail, facebook, skyback.ru, couchtuner.

It was blocking the script because it contained "Miner" in it. Now when you add a site to the exceptions list, it allows the scripts for that site. In the next update, I will allow you to add specific scripts to the white-list instead of just the entire site. That should make the white-list feature complete. I've also been requested to add the option to "add this site to white list" via a button.
